import { type Metadata } from 'next'
import { AuthProvider } from '@/context/userContext';
import '../../(main)/globals.css'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <header>
        <h1 className="text-4xl font-bold text-center mt-10">Auth Layout</h1>
      </header>
      {children}
    </div>
  );
}


