import { type Metadata } from 'next'
import '@/app/(main)/globals.css'
import AdminLayoutClient from '@/components/admin/AdminLayoutClient'

export const metadata: Metadata = {
  title: 'Eventify',
  description: 'Generated by create next app',
}

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return <AdminLayoutClient>{children}</AdminLayoutClient>
}