import { type Metadata } from 'next'
import Navbar from "@/components/shared/Navbar";
import './globals.css'
import Footer from '@/components/shared/Footer';

export const metadata: Metadata = {
  title: 'Eventify',
  description: 'Generated by create next app',
}

export default function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
